language: c
compiler:
  - clang
python:
  - "3.5"
before_install:
  - sudo apt-get install -y libgmp-dev valgrind
script:
  - cd c
  - ./build.sh
  - cd -
  - cd python/tests
  - ./run_tests.py
  - cd -
