language: c, python
compiler:
  - clang
  - gcc
python:
  - "2.7"
  - "3.5"
before_install:
  - sudo apt-get install -y libgmp-dev valgrind
script:
  - cd c
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build . --target all
  - cmake --build . --target test
  - ./test1
  - cd ../..
  - cd python/tests
  - ./run_tests.py
  - cd -
